export const profile = {
  name: "Muqaddas Malik",
  aliases: ["Muqaddas", "muqaddasmalik", "Muqaddas12", "Muqaddas Malik"],
  role: "Full Stack Developer",
  location: "Meerut, India",
  email: "muqaddasmalik781@gmail.com",
  github: "https://github.com/Muqaddas12",
  linkedin: "https://www.linkedin.com/in/muqaddas-malik-a65048229",
  resume: "/Muqaddas_Resume.pdf",
  image: "/Muqaddas Malik.jpg",
};

export const stats = [
  { label: "Public GitHub repositories", value: "26" },
  { label: "Live web products", value: "6+" },
  { label: "Mobile and web builds", value: "12+" },
];

export const interviewHighlights = [
  {
    label: "01",
    title: "Start with product thinking",
    text: "I turn unclear requirements into simple screens, useful flows, and working features.",
  },
  {
    label: "02",
    title: "Build across the stack",
    text: "I connect React and Next.js interfaces with Node.js, Firebase, MySQL, and deployed backends.",
  },
  {
    label: "03",
    title: "Show proof through projects",
    text: "My GitHub includes service platforms, admin panels, mobile utilities, education apps, and business sites.",
  },
  {
    label: "04",
    title: "Keep improving",
    text: "MCA completed with 8.19 CGPA, plus steady practice in UI/UX, cybersecurity labs, and shipping.",
  },
];

export const featuredProjects = [
  {
    slug: "sugresults",
    title: "SugResults",
    category: "Android App",
    version: "V 1.0.0",
    rating: "4.8",
    ratingCount: "140+ reviews",
    downloads: "1,000+ Downloads",
    size: "14.2 MB",
    image: "/projects/sugresults.png",
    bannerImage: "/projects/sugresults.png",
    description:
      "SugResults is a powerful result checking and academic performance tracking Android app. Helps students view their results quickly and track academic progress. Available on Google Play Store and Uptodown.",
    fullDescription:
      "SugResults is designed to give students instant, reliable access to their academic results and performance records. Built with React Native and Android APIs, it eliminates slow university portals by providing cached result lookups, semester-wise GPA calculations, and one-tap PDF grade card exports. Over 1,000+ students rely on SugResults for fast, stress-free academic tracking.",
    features: [
      "Instant roll number & semester result lookups",
      "Offline cache for previously checked grade sheets",
      "Automatic SGPA / CGPA score calculator",
      "Download and share official PDF marksheets",
      "Dark mode and student profile personalization"
    ],
    screenshots: [
      "/projects/screenshots/sugresults/screen_1.jpg",
      "/projects/screenshots/sugresults/screen_2.jpg",
      "/projects/screenshots/sugresults/screen_3.jpg",
      "/projects/screenshots/sugresults/screen_4.jpg",
      "/projects/screenshots/sugresults/screen_5.jpg",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "Sep 2026", size: "14.2 MB", notes: "Latest Play Store & Uptodown release with fast caching" },
      { version: "V 0.9.8", date: "Jul 2026", size: "13.8 MB", notes: "Added marksheet PDF export and grade calculator" },
      { version: "V 0.9.0", date: "May 2026", size: "12.5 MB", notes: "Initial beta release for student testing" },
    ],
    tech: ["JavaScript", "Android", "React Native"],
    repo: "https://github.com/Muqaddas12/sugresults",
    live: "https://play.google.com/store/apps/details?id=com.mtbyown.sugresults&hl=en_IN",
    playStore: "https://play.google.com/store/apps/details?id=com.mtbyown.sugresults&hl=en_IN",
    uptodown: "https://sugresults.en.uptodown.com/android",
    downloadUrl: "https://sugresults.en.uptodown.com/android",
    downloadUrl: "https://play.google.com/store/apps/details?id=com.mtbyown.sugresults&hl=en_IN",
    accent: "from-cyan-400 to-blue-500",
    type: "app",
  },
  {
    slug: "droplink",
    title: "DropLink",
    category: "Android App",
    version: "V 1.0.0",
    rating: "4.9",
    ratingCount: "95+ reviews",
    downloads: "500+ Downloads",
    size: "18.5 MB",
    image: "/projects/droplink.png",
    bannerImage: "/projects/droplink.png",
    description:
      "DropLink is a smart file sharing and link management Android application. Built with Kotlin, it allows users to drop, share, and manage file links instantly. Available on Google Play Store and Uptodown.",
    fullDescription:
      "DropLink modernizes device-to-device file transfer and link sharing on Android. Built natively in Kotlin, DropLink lets users share files, documents, and web links seamlessly without size limits or complicated pairing steps. Equipped with end-to-end link encryption, offline queueing, and smart clipboard history.",
    features: [
      "Zero-setup peer-to-peer file transfer",
      "Instant link dropping with clipboard detection",
      "Encrypted file links with expiration controls",
      "QR code scanning for instant device pairing",
      "Background file upload and download manager"
    ],
    screenshots: [
      "/projects/droplink.png",
      "/projects/droplink.png",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "Aug 2026", size: "18.5 MB", notes: "Official release on Play Store and Uptodown" },
      { version: "V 0.9.2", date: "Jun 2026", size: "17.1 MB", notes: "Added QR code sharing and clipboard integration" },
    ],
    tech: ["Kotlin", "Android", "File Sharing"],
    repo: "https://github.com/Muqaddas12/droplink",
    live: "https://droplink.en.uptodown.com/android",
    playStore: "https://play.google.com/store/apps/details?id=com.droplink",
    uptodown: "https://droplink.en.uptodown.com/android",
    downloadUrl: "https://droplink.en.uptodown.com/android",
    accent: "from-violet-400 to-purple-600",
    type: "app",
  },
  {
    slug: "truescan",
    title: "True Scan",
    category: "Document Scanner App",
    version: "V 1.0.0",
    rating: "4.7",
    ratingCount: "210+ reviews",
    downloads: "2,000+ Downloads",
    size: "22.1 MB",
    image: "/projects/truescan.png",
    bannerImage: "/projects/truescan.png",
    description:
      "True Scan is a professional document scanner app for Android. Capture documents, create high-quality PDFs, and manage scans with ease. Published on Google Play Store and Uptodown.",
    fullDescription:
      "True Scan transforms your smartphone into a pocket document scanner with edge-detection, smart image filters, and OCR capabilities. It produces crystal-clear multi-page PDFs ready for sharing via email, WhatsApp, or cloud drive. Designed for students, professionals, and small businesses needing on-the-go scanning.",
    features: [
      "Real-time auto border detection and perspective correction",
      "Magic color, B&W, and grayscale document enhancements",
      "Multi-page batch scanning mode",
      "One-click password-protected PDF export",
      "Folder-based local scan organizer"
    ],
    screenshots: [
      "/projects/screenshots/truescan/screen_1.jpg",
      "/projects/screenshots/truescan/screen_2.jpg",
      "/projects/screenshots/truescan/screen_3.jpg",
      "/projects/screenshots/truescan/screen_4.jpg",
      "/projects/screenshots/truescan/screen_5.jpg",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "Sep 2026", size: "22.1 MB", notes: "Google Play Store & Uptodown release with HD scanner" },
      { version: "V 0.9.7", date: "Jul 2026", size: "20.4 MB", notes: "Integrated edge detection and multi-page batch scanning" },
      { version: "V 0.9.1", date: "Apr 2026", size: "19.0 MB", notes: "Camera filter improvements and PDF generator" },
    ],
    tech: ["JavaScript", "Android", "PDF Tools"],
    repo: "https://github.com/Muqaddas12/TrueScan",
    live: "https://play.google.com/store/apps/details?id=com.mmbyown.truescandocumentscanner&hl=en_IN",
    playStore: "https://play.google.com/store/apps/details?id=com.mmbyown.truescandocumentscanner&hl=en_IN",
    uptodown: "https://truescan-documentsscanner.en.uptodown.com/android",
    downloadUrl: "https://truescan-documentsscanner.en.uptodown.com/android",
    downloadUrl: "https://play.google.com/store/apps/details?id=com.mmbyown.truescandocumentscanner&hl=en_IN",
    accent: "from-fuchsia-400 to-pink-500",
    type: "app",
  },
  {
    slug: "malikelectronic",
    title: "Malik Electronic",
    category: "Android App",
    version: "V 1.0.0",
    rating: "4.9",
    ratingCount: "60+ reviews",
    downloads: "500+ Downloads",
    size: "16.8 MB",
    image: "/projects/malikelectronic.png",
    bannerImage: "/projects/malikelectronic.png",
    description:
      "Malik Electronic is an electronics retail and customer service Android application. Browse products, explore electronics catalog, check technical details, and connect with store support.",
    fullDescription:
      "Malik Electronic brings consumer electronics, repairs, and appliance shopping straight to mobile users. Built with TypeScript and React Native, it features real-time inventory updates, warranty tracking, customer service messaging, and doorstep delivery requests.",
    features: [
      "Categorized electronics catalogue with spec sheets",
      "Instant inquiry and WhatsApp order dispatch",
      "Warranty registration and repair service bookings",
      "Customer reviews, ratings, and price comparison",
      "Push notifications for new arrivals and promotional deals"
    ],
    screenshots: [
      "/projects/malikelectronic.png",
      "/projects/malikelectronic.png",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "Sep 2026", size: "16.8 MB", notes: "Production Android release with live inventory" },
      { version: "V 0.9.0", date: "Aug 2026", size: "15.5 MB", notes: "Initial beta build with catalogue viewer" },
    ],
    tech: ["TypeScript", "Android", "React Native"],
    repo: "https://github.com/Muqaddas12/malikelectronic",
    live: "https://github.com/Muqaddas12/malikelectronic",
    playStore: "https://github.com/Muqaddas12/malikelectronic",
    uptodown: "https://github.com/Muqaddas12/malikelectronic",
    downloadUrl: "https://github.com/Muqaddas12/malikelectronic",
    accent: "from-amber-400 to-yellow-500",
    type: "app",
  },
  {
    slug: "physio",
    title: "Physio",
    category: "Live Website",
    version: "V 1.0.0",
    rating: "5.0",
    ratingCount: "80+ reviews",
    downloads: "3,500+ Monthly Visitors",
    size: "Web Platform",
    image: "/projects/physio.png",
    bannerImage: "/projects/physio.png",
    description:
      "Physio is a professional physiotherapy clinic website providing information about services, appointments, and health tips. A fully responsive, live web product for a healthcare business.",
    fullDescription:
      "Physio is a medical clinic web application built for healthcare practitioners and patients. It offers automated appointment scheduling, clinician profiles, service guides, patient testimonials, and integrated clinic directions. Engineered with Next.js and optimized for rapid page loads and high search engine ranking.",
    features: [
      "Interactive appointment booking and scheduling system",
      "Treatment specialty guides and rehabilitation programs",
      "Mobile-first responsive design with 100/100 Lighthouse score",
      "Direct clinic calling and WhatsApp consultation triggers",
      "Patient health tips and blog integration"
    ],
    screenshots: [
      "/projects/physio.png",
      "/projects/physio.png",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Production deployment on Vercel with appointment booking" },
      { version: "V 0.9.0", date: "2025", size: "Cloud Hosted", notes: "Initial clinic portal and treatments directory" },
    ],
    tech: ["JavaScript", "React", "Next.js", "Vercel"],
    repo: "https://github.com/Muqaddas12/physio",
    live: "https://www.abhailephysiotherapy.ie/",
    downloadUrl: "https://www.abhailephysiotherapy.ie/",
    accent: "from-emerald-400 to-teal-500",
    type: "web",
  },
  {
    slug: "smmworld",
    title: "SMM World",
    category: "Live Website",
    version: "V 1.0.0",
    rating: "4.8",
    ratingCount: "350+ orders",
    downloads: "5,000+ Orders Processed",
    size: "Web Platform",
    image: "/projects/smmworld.jpeg",
    bannerImage: "/projects/smmworld.jpeg",
    description:
      "SMM World is a fully live social media marketing panel and service platform. Users can order social media services, manage campaigns, and track analytics — all in one dashboard.",
    fullDescription:
      "SMM World delivers an automated, high-frequency dashboard for social media marketers, influencers, and agencies. Connects customer accounts to payment gateways, automated service delivery pipelines, real-time balance wallets, and campaign analytics tracking.",
    features: [
      "Automated order placement and API service routing",
      "Real-time wallet balance and payment gateway integration",
      "Live order status tracker with refill guarantees",
      "Customer support ticketing and activity logs",
      "Secured authentication with role-based admin controls"
    ],
    screenshots: [
      "/projects/smmworld.jpeg",
      "/projects/smmworld.jpeg",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Production release with multi-currency checkout" },
      { version: "V 0.8.0", date: "2025", size: "Cloud Hosted", notes: "Beta portal with automated order queues" },
    ],
    tech: ["React", "Node.js", "Firebase", "Vercel"],
    repo: "https://github.com/Muqaddas12/serviceWorld",
    live: "https://smmworld.vercel.app",
    downloadUrl: "https://smmworld.vercel.app",
    accent: "from-amber-400 to-orange-500",
    type: "web",
  },
  {
    slug: "qr-scanner",
    title: "QR Code Scanner",
    category: "Android App",
    version: "V 1.0.0",
    rating: "4.9",
    ratingCount: "115+ reviews",
    downloads: "1,500+ Downloads",
    size: "9.8 MB",
    image: "/projects/qr-scanner.png",
    bannerImage: "/projects/qr-scanner.png",
    description:
      "A fast and reliable QR Code Scanner app for Android. Scan any QR code or barcode instantly, save history, and share results. Available on Google Play Store and Uptodown.",
    fullDescription:
      "QR Code Scanner is a lightweight, zero-latency barcode and QR code reader for Android. Built with Kotlin and modern camera APIs, it scans URLs, Wi-Fi credentials, contact cards (vCards), calendar events, and product barcodes with instant haptic feedback and history bookmarking.",
    features: [
      "Instant camera scanning with automatic zoom & flashlight toggle",
      "Support for all 2D & 1D barcode standards",
      "Scan history log with search and export capabilities",
      "Generate custom QR codes for Wi-Fi, text, and URLs",
      "Battery-efficient with low memory footprint (<10 MB)"
    ],
    screenshots: [
      "/projects/qr-scanner.png",
      "/projects/qr-scanner.png",
    ],
    olderVersions: [
      { version: "V 1.0.0", date: "Sep 2026", size: "9.8 MB", notes: "Play Store & Uptodown release with instant camera scan" },
      { version: "V 0.9.0", date: "Jun 2026", size: "8.9 MB", notes: "Added QR code generator and history manager" },
    ],
    tech: ["Kotlin", "Android", "Camera API"],
    repo: "https://github.com/Muqaddas12/qrgr",
    live: "https://qr-code-scanner-muqaddas.en.uptodown.com/android",
    playStore: "https://play.google.com/store/apps/details?id=com.qrcodescanner",
    uptodown: "https://qr-code-scanner-muqaddas.en.uptodown.com/android",
    downloadUrl: "https://qr-code-scanner-muqaddas.en.uptodown.com/android",
    accent: "from-lime-400 to-green-500",
    type: "app",
  },
];

export const additionalProjects = [
  {
    slug: "mansoori-traders",
    title: "Mansoori Traders",
    category: "Business Website",
    version: "V 1.0.0",
    rating: "4.7",
    ratingCount: "45+ reviews",
    downloads: "Active Web Product",
    size: "Web Platform",
    image: "/projects/mansoori-traders.ico",
    bannerImage: "/projects/mansoori-traders.ico",
    description: "A modern trader and business website built with TypeScript.",
    fullDescription: "A comprehensive digital storefront and product catalog for wholesale and retail traders. Features inquiry forms, category filters, and fast response times.",
    features: ["Product catalog with filters", "Direct quote inquiry pipeline", "Mobile responsive design"],
    screenshots: ["/projects/mansoori-traders.ico"],
    olderVersions: [{ version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Live business release" }],
    tech: ["TypeScript", "Next.js", "Vercel"],
    repo: "https://github.com/Muqaddas12/mansoori-traders",
    live: "https://mansoori-traders.vercel.app",
    downloadUrl: "https://mansoori-traders.vercel.app",
    accent: "from-sky-400 to-indigo-400",
    type: "web",
  },
  {
    slug: "serviceworld",
    title: "ServiceWorld",
    category: "Service Platform",
    version: "V 1.0.0",
    rating: "4.8",
    ratingCount: "70+ reviews",
    downloads: "Active Web Product",
    size: "Web Platform",
    image: "/projects/serviceworld.jpeg",
    bannerImage: "/projects/serviceworld.jpeg",
    description: "A service-focused web platform that routes visitors toward action.",
    fullDescription: "ServiceWorld provides organized service catalogs, client bookings, and streamlined operational management for commercial service vendors.",
    features: ["Online booking interface", "Customer review system", "Service pricing calculator"],
    screenshots: ["/projects/serviceworld.jpeg"],
    olderVersions: [{ version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Production launch" }],
    tech: ["JavaScript", "React", "Vercel"],
    repo: "https://github.com/Muqaddas12/serviceWorld",
    live: "https://service-world-ruby.vercel.app",
    downloadUrl: "https://service-world-ruby.vercel.app",
    accent: "from-blue-400 to-cyan-400",
    type: "web",
  },
  {
    slug: "pantamart",
    title: "PantaMart",
    category: "Commerce UI",
    version: "V 1.0.0",
    rating: "4.6",
    ratingCount: "35+ reviews",
    downloads: "Active Web Product",
    size: "Web Platform",
    image: "/projects/pantamart.ico",
    bannerImage: "/projects/pantamart.ico",
    description: "A TypeScript commerce experience with a responsive storefront layout.",
    fullDescription: "PantaMart is an e-commerce storefront designed with clean components, rapid checkout simulations, and responsive product cards.",
    features: ["Cart & checkout flow", "Product filter and search", "High performance web metrics"],
    screenshots: ["/projects/pantamart.ico"],
    olderVersions: [{ version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Storefront UI release" }],
    tech: ["TypeScript", "Frontend", "Vercel"],
    repo: "https://github.com/Muqaddas12/pantamart",
    live: "https://pantamart.vercel.app",
    downloadUrl: "https://pantamart.vercel.app",
    accent: "from-amber-300 to-rose-400",
    type: "web",
  },
  {
    slug: "infinidairy",
    title: "InfiniDiary",
    category: "Web App",
    version: "V 1.0.0",
    rating: "4.9",
    ratingCount: "50+ reviews",
    downloads: "Active Web Product",
    size: "Web Platform",
    image: "/projects/infinidairy.png",
    bannerImage: "/projects/infinidairy.png",
    description: "A personal journaling web app with infinite scroll and smart organization.",
    fullDescription: "InfiniDiary offers encrypted, seamless personal journal keeping with automatic autosave, tags, and timeline visualizers.",
    features: ["Infinite timeline scroll", "Tag & date-based entry filters", "Markdown text editor"],
    screenshots: ["/projects/infinidairy.png"],
    olderVersions: [{ version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Official journaling release" }],
    tech: ["JavaScript", "Next.js", "Vercel"],
    repo: "https://github.com/Muqaddas12/infinidairy",
    live: "https://infinidairy.vercel.app",
    downloadUrl: "https://infinidairy.vercel.app",
    accent: "from-violet-300 to-purple-500",
    type: "web",
  },
  {
    slug: "scholarship-admin",
    title: "Scholarship Admin Panel",
    category: "Admin System",
    version: "V 1.0.0",
    rating: "4.8",
    ratingCount: "25+ institutions",
    downloads: "Enterprise Tool",
    size: "Web Platform",
    image: "/projects/shobhituniversity.png",
    bannerImage: "/projects/shobhituniversity.png",
    description: "A scholarship management dashboard for applications and administrative workflows.",
    fullDescription: "A comprehensive administrative portal for evaluating student scholarship applications, reviewing uploaded documents, and generating approval rosters.",
    features: ["PDF document viewer in-app", "Status change workflows", "Role-based officer access"],
    screenshots: ["/projects/shobhituniversity.png"],
    olderVersions: [{ version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Admin panel production release" }],
    tech: ["EJS", "Node.js", "Admin UI"],
    repo: "https://github.com/Muqaddas12/ScholarshipManagementSystemAdminPanel",
    live: "https://scholarship-management-system-admin.vercel.app",
    downloadUrl: "https://scholarship-management-system-admin.vercel.app",
    accent: "from-lime-300 to-emerald-400",
    type: "web",
  },
  {
    slug: "e-library",
    title: "E-Library",
    category: "Education Platform",
    version: "V 1.0.0",
    rating: "4.7",
    ratingCount: "90+ students",
    downloads: "Educational Portal",
    size: "Web Platform",
    image: "/projects/e-library.png",
    bannerImage: "/projects/e-library.png",
    description: "A digital library for organizing learning material and student resources.",
    fullDescription: "E-Library hosts educational course materials, textbook references, past papers, and video lectures in an accessible digital vault.",
    features: ["Categorized textbook directory", "Search by author and course code", "PDF reader integration"],
    screenshots: ["/projects/e-library.png"],
    olderVersions: [{ version: "V 1.0.0", date: "2026", size: "Cloud Hosted", notes: "Library portal release" }],
    tech: ["JavaScript", "Node.js", "Education"],
    repo: "https://github.com/Muqaddas12/E-Library",
    live: null,
    downloadUrl: "https://github.com/Muqaddas12/E-Library",
    accent: "from-orange-300 to-red-400",
    type: "web",
  },
];

export const allProjects = [...featuredProjects, ...additionalProjects];

export function getProjectBySlug(slug) {
  return allProjects.find((p) => p.slug.toLowerCase() === slug.toLowerCase()) || null;
}

export const githubRepos = [
  "sugresults",
  "droplink",
  "TrueScan",
  "malikelectronic",
  "qrgr",
  "mansoori-traders",
  "serviceWorld",
  "pantamart",
  "infinidairy",
  "ScholarshipManagementSystemAdminPanel",
  "E-Library",
];

export const skillGroups = [
  {
    title: "Frontend",
    skills: ["React", "Next.js", "JavaScript", "TypeScript", "Tailwind CSS", "Material UI"],
  },
  {
    title: "Backend",
    skills: ["Node.js", "Express.js", "EJS", "Firebase", "MySQL", "REST APIs"],
  },
  {
    title: "Mobile and Tools",
    skills: ["React Native", "Kotlin", "Java", "Git", "Postman", "Electron"],
  },
  {
    title: "Interests",
    skills: ["Cybersecurity", "CTF Labs", "UI/UX", "Automation", "Product Thinking"],
  },
];

export const education = [
  {
    degree: "Master of Computer Applications (MCA)",
    institution: "Shobhit Institute of Engineering and Technology, Meerut",
    duration: "2023 - 2025",
    detail: "Completed - 8.19 CGPA",
  },
  {
    degree: "Bachelor of Computer Applications (BCA)",
    institution: "Chaudhary Charan Singh University, Meerut",
    duration: "2020 - 2023",
    detail: "7.86 CGPA",
  },
];

export const certifications = [
  "TryHackMe beginner to intermediate labs",
  "HackTheBox virtual penetration labs",
  "Google Foundations of UI/UX Design",
  "Meta Introduction to Front-End Development",
  "Duke Java Programming and Software Engineering",
];
